name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: yarn install

      - name: Run tests and collect coverage
        run: yarn test --coverage

      - name: List coverage directory
        run: ls -R coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        with:
          sonar-project-key: "Costanza22_front-cloud"
          sonar-host-url: "https://sonarcloud.io"
          sonar-login: ${{ secrets.SONAR_TOKEN }}
          sonar.javascript.lcov.reportPaths: "coverage/**/*.json"  # Tente um caminho mais flexível
