name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: yarn install

      - name: Run tests and collect coverage
        run: yarn test --coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        with:
          sonar-project-key: "Costanza22_front-cloud"  # Chave do projeto no SonarCloud
          sonar-host-url: "https://sonarcloud.io"   # URL do SonarCloud
          sonar-login: ${{ secrets.SONAR_TOKEN }}    # Token do SonarCloud
          sonar.javascript.lcov.reportPaths: "coverage/lcov-report/lcov-report.json"  # Caminho para o relatório de cobertura
